import api from './axios'

export const getHRDashboard = () => api.get('/hr/dashboard')
export const getDepartments = (params) => api.get('/hr/departments', { params })
export const getDepartment = (id) => api.get(`/hr/departments/${id}`)
export const createDepartment = (data) => api.post('/hr/departments', data)
export const updateDepartment = (id, data) => api.put(`/hr/departments/${id}`, data)
export const deleteDepartment = (id) => api.delete(`/hr/departments/${id}`)
export const getEmployees = (params) => api.get('/hr/employees', { params })
export const getEmployee = (id) => api.get(`/hr/employees/${id}`)
export const createEmployee = (data) => api.post('/hr/employees', data)
export const updateEmployee = (id, data) => api.put(`/hr/employees/${id}`, data)
export const getAttendance = (params) => api.get('/hr/attendance', { params })
export const checkIn = () => api.post('/hr/attendance/check-in')
export const checkOut = () => api.post('/hr/attendance/check-out')
export const getLeaveRequests = (params) => api.get('/hr/leave-requests', { params })
export const createLeaveRequest = (data) => api.post('/hr/leave-requests', data)
export const approveLeave = (id) => api.put(`/hr/leave-requests/${id}/approve`)
export const rejectLeave = (id, data) => api.put(`/hr/leave-requests/${id}/reject`, data)
export const getPayrollRecords = (params) => api.get('/hr/payroll', { params })
export const createPayrollRecord = (data) => api.post('/hr/payroll', data)
export const updatePayrollRecord = (id, data) => api.put(`/hr/payroll/${id}`, data)
export const getEmployeeDocuments = (params) => api.get('/hr/documents', { params })
export const createEmployeeDocument = (data) => api.post('/hr/documents', data)
export const deleteEmployeeDocument = (id) => api.delete(`/hr/documents/${id}`)
export const getOrgChart = () => api.get('/hr/org/chart')
export const getEmployeesByDepartment = (deptId) => api.get(`/hr/departments/${deptId}/employees`)

export const getMyEmployee = () => api.get('/me/employee')
export const getMyLeaveRequests = (params) => api.get('/me/leave-requests', { params })
export const createMyLeaveRequest = (data) => api.post('/me/leave-requests', data)
export const getMyLeaveBalance = () => api.get('/me/leave-balance')
export const getMyPayroll = (params) => api.get('/me/payroll', { params })
export const getMyAttendance = (params) => api.get('/me/attendance', { params })
export const getMyLoans = (params) => api.get('/me/loans', { params })
export const createMyLoan = (data) => api.post('/me/loans', data)

export const getDeductions = (params) => api.get('/hr/deductions', { params })
export const createDeduction = (data) => api.post('/hr/deductions', data)
export const updateDeduction = (id, data) => api.put(`/hr/deductions/${id}`, data)
export const deleteDeduction = (id) => api.delete(`/hr/deductions/${id}`)

export const getRequests = (params) => api.get('/hr/requests', { params })
export const createRequest = (data) => api.post('/hr/requests', data)
export const approveRequest = (id) => api.put(`/hr/requests/${id}/approve`)
export const rejectRequest = (id, data) => api.put(`/hr/requests/${id}/reject`, data)

export const getSystemConfig = () => api.get('/hr/system-config')
export const updateSystemConfig = (data) => api.put('/hr/system-config', data)
export const getBranches = () => api.get('/hr/branches')
export const createBranch = (data) => api.post('/hr/branches', data)
export const updateBranch = (id, data) => api.put(`/hr/branches/${id}`, data)
export const deleteBranch = (id) => api.delete(`/hr/branches/${id}`)
