import api from './axios'

export const getHRDashboard = () => api.get('/hr/dashboard')
export const getDepartments = (params) => api.get('/hr/departments', { params })
export const getDepartment = (id) => api.get(`/hr/departments/${id}`)
export const createDepartment = (data) => api.post('/hr/departments', data)
export const updateDepartment = (id, data) => api.put(`/hr/departments/${id}`, data)
export const deleteDepartment = (id) => api.delete(`/hr/departments/${id}`)
export const getEmployees = (params) => api.get('/hr/employees', { params })
export const getEmployee = (id) => api.get(`/hr/employees/${id}`)
export const createEmployee = (data) => api.post('/hr/employees', data)
export const updateEmployee = (id, data) => api.put(`/hr/employees/${id}`, data)
export const getAttendance = (params) => api.get('/hr/attendance', { params })
export const checkIn = () => api.post('/hr/attendance/check-in')
export const checkOut = () => api.post('/hr/attendance/check-out')
export const getLeaveRequests = (params) => api.get('/hr/leave-requests', { params })
export const createLeaveRequest = (data) => api.post('/hr/leave-requests', data)
export const approveLeave = (id) => api.put(`/hr/leave-requests/${id}/approve`)
export const rejectLeave = (id, data) => api.put(`/hr/leave-requests/${id}/reject`, data)
export const getPayrollRecords = (params) => api.get('/hr/payroll', { params })
export const createPayrollRecord = (data) => api.post('/hr/payroll', data)
export const updatePayrollRecord = (id, data) => api.put(`/hr/payroll/${id}`, data)
export const getEmployeeDocuments = (params) => api.get('/hr/documents', { params })
export const createEmployeeDocument = (data) => api.post('/hr/documents', data)
export const deleteEmployeeDocument = (id) => api.delete(`/hr/documents/${id}`)
